services:
  - type: web
    name: japanese-ocr-dictionary
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn server:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.16"
      - key: TESSDATA_PREFIX
        value: "/opt/render/.local/share/tesseract-ocr/4.00/tessdata/"
